version: 2.1
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/matsuyoshi30/gohjong
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v
