version: 2.1
general:
  artifacts:
    - "coverage.out"
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/matsuyoshi30/gohjong
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint github.com/haya14busa/goverage
      - run: golint ./...
      - run: go vet ./...
      - run: goverage -v -coverprofile=coverage.out ./...
      - run: go tool cover -html coverage.out -o coverage.html
      - store_artifacts:
          path: coverage.out
          destination: coverage.out
      - store_artifacts:
          path: coverage.html
          destination: coverage.html
